[programs.localnet]
liftskit_membership_v4 = "Gqsr3fjeaVBWNrr4NDetcZaNZYNWxdiN3EQZy5wtzpH9"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/travis/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
